// <auto-generated />
namespace MediatRApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class init_structure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init_structure));
        
        string IMigrationMetadata.Id
        {
            get { return "201608170735203_init_structure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
